# Generated by Django 5.1.5 on 2025-02-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
