# Generated by Django 5.1.5 on 2025-02-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0002_alter_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='provincia',
        ),
    ]
