# Generated by Django 5.1.5 on 2025-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0003_remove_customuser_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
