# Generated by Django 5.1.5 on 2025-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_nacimiento',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nacionalidad',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
