# Generated by Django 5.1.5 on 2025-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0005_rename_direccion_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(choices=[('ES', 'España'), ('FR', 'Francia'), ('IT', 'Italia'), ('DE', 'Alemania'), ('UK', 'Reino Unido'), ('US', 'Estados Unidos'), ('MX', 'México'), ('AR', 'Argentina')], default='ES', max_length=100),
        ),
    ]
