# Generated by Django 5.1.5 on 2025-02-12 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0006_alter_customuser_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(choices=[('ES', 'Spanish'), ('FR', 'French'), ('IT', 'Italian'), ('DE', 'German'), ('UK', 'British'), ('US', 'American'), ('MX', 'Mexican'), ('AR', 'Argentinian')], default='ES', max_length=100),
        ),
        migrations.CreateModel(
            name='TouristGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
