# Generated by Django 5.1.5 on 2025-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0007_alter_customuser_nationality_touristguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('historical-sites', 'Historical Sites'), ('cultural-experiences', 'Cultural Experiences'), ('gastronomy', 'Gastronomy'), ('shopping', 'Shopping'), ('outdoor-activities', 'Outdoor Activities')], max_length=50)),
                ('visit_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('google_maps_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
