# Generated by Django 5.1.5 on 2025-02-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0008_touristplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristplace',
            name='description',
        ),
        migrations.AddField(
            model_name='touristplace',
            name='adequacy',
            field=models.IntegerField(choices=[(0, 'Adequate for all types of tourists'), (1, 'Adequate only for people traveling for work'), (2, 'Adequate only for people traveling in partners'), (3, 'Adequate only for people traveling with family (18+ years old)'), (4, 'Adequate only for people traveling with family (children below 18)')], default=0),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='activity_type',
            field=models.CharField(choices=[('Historical Sites', 'Historical Sites'), ('Cultural Experiences', 'Cultural Experiences'), ('Gastronomy', 'Gastronomy'), ('Shopping', 'Shopping'), ('Outdoor Activities', 'Outdoor Activities'), ('Literary', 'Literary'), ('Scientific', 'Scientific'), ('Entertainment', 'Entertainment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='visit_duration',
            field=models.IntegerField(),
        ),
    ]
