# Generated by Django 5.1.5 on 2025-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0009_remove_touristplace_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='visit_duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
    ]
