# Generated by Django 5.1.5 on 2025-02-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0010_alter_touristplace_visit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='city',
            field=models.CharField(default='Sevilla', max_length=255),
        ),
    ]
