# Generated by Django 5.1.5 on 2025-02-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0011_touristplace_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='activity_type',
            field=models.CharField(choices=[('historical-sites', 'historical-sites'), ('cultural-experiences', 'cultural-experiences'), ('gastronomy', 'gastronomy'), ('shopping', 'shopping'), ('outdoor', 'outdoor'), ('literary', 'literary'), ('scientific', 'scientific'), ('entertainment', 'entertainment')], max_length=50),
        ),
    ]
