# Generated by Django 5.1.5 on 2025-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0012_alter_touristplace_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristguide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='touristguide',
            name='title',
        ),
        migrations.RemoveField(
            model_name='touristguide',
            name='user',
        ),
        migrations.AddField(
            model_name='touristguide',
            name='available_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='city',
            field=models.CharField(default='Seville', max_length=255),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='ending_point',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='guide_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='starting_point',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='tour_budget',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='tour_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='travel_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
