# Generated by Django 5.1.5 on 2025-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0013_remove_touristguide_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
