# Generated by Django 5.1.5 on 2025-03-19 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0015_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristguide',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_guides', to=settings.AUTH_USER_MODEL),
        ),
    ]
