# Generated by Django 5.1.5 on 2025-04-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySeville', '0018_touristplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(choices=[('ES', 'Spanish'), ('FR', 'French'), ('IT', 'Italian'), ('DE', 'German'), ('UK', 'British'), ('US', 'American'), ('MX', 'Mexican'), ('AR', 'Argentinian'), ('BR', 'Brazilian'), ('CA', 'Canadian'), ('JP', 'Japanese'), ('CN', 'Chinese'), ('IN', 'Indian'), ('RU', 'Russian'), ('NL', 'Dutch'), ('SE', 'Swedish'), ('NO', 'Norwegian'), ('PT', 'Portuguese'), ('AU', 'Australian'), ('BE', 'Belgian'), ('CH', 'Swiss'), ('CL', 'Chilean'), ('CO', 'Colombian'), ('PE', 'Peruvian'), ('VE', 'Venezuelan')], default='ES', max_length=100),
        ),
    ]
